# Generated by Django 4.0.4 on 2022-05-16 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_company_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 5, 16, 12, 12, 6, 132332)),
            preserve_default=False,
        ),
    ]
