# Generated by Django 4.0.4 on 2022-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_company_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimg',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
