# Generated by Django 4.0.4 on 2022-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_companyimg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimg',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
