# Generated by Django 4.0.4 on 2022-05-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_companyimg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimg',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.company'),
        ),
    ]
