# Generated by Django 4.0.4 on 2022-05-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_companyimg_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imageboard/images'),
        ),
    ]
