# Generated by Django 4.0.4 on 2022-05-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_company_img1_alter_company_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='img1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company1', to='manager.companyimg'),
        ),
        migrations.AlterField(
            model_name='company',
            name='img2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company2', to='manager.companyimg'),
        ),
    ]
