# Generated by Django 4.0.4 on 2022-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_company_img1_alter_company_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
